mail:
  receiver:
    # qq email
    store-host: imap.qq.com
    transport-host: smtp.qq.com
    port: 993
    # email username
    username: xxx
    # IMAP authorization code
    password: xxx
    store-protocol: imap
    transport-protocol: smtp
    ssl: true
    idle: true
    poll-freq: 5000
    run-node: true
    run-node-key: ARTEMIS_JOB_NODE
    run-node-value: 1
    cron: 0 0/10 * * * ?

logging:
  level:
    root: debug
