mail:
  receiver:
    # qq email
    store-host: imap.qq.com
    transport-host: smtp.qq.com
    imap-port: 993
    smtp-port: 993
    # email username
    username: xxx@qq.com
    # authorization code
    password: xxx
    store-protocol: imap
    transport-protocol: smtp
    ssl: true
    idle: true
    poll-freq: 5000
    run-node: true
    run-node-key: ARTEMIS_JOB_NODE
    run-node-value: 1
    cron: 0 0/9 * * * ?

logging:
  level:
    root: debug

# spring-boot 2.6 开始默认禁止依赖循环
spring:
  main:
    allow-circular-references: true
